### ISSUE TITLE
ldap not installed

### ISSUE THREAD

**Issue by cgrima** [grimy55/docker_i-librarian#1]
In Tools/InstallationDetails the ldap binaries are indicated as "not installed".

**Comment by cgrima** [comment]
Don't know yet how to handle the issue, I'm not familiar with ldap.
Tried to install "slapd" and "ldap-utils" packages packages but nothing changed.

**Comment by mkucej** [comment]
LDAP normally requires php5-ldap package.

**Comment by cgrima** [comment]
That was it. It is fixed. Thanks.

**Comment by grimy55** [comment]
That was it. It is fixed in the next issue. Thanks.
