### ISSUE TITLE
PDF do not load after Update to 5.9.1 or 5.9.2

### ISSUE THREAD

**Issue by arunoruto** [grimy55/docker_i-librarian#11]
I updated two instances of iLibrarian and both of them are unable to display the PDFs in the inbuilt preview.
Looking up in the developer console, an error is presented which states:
`Failed to load resource: the server responded with a status of 500 ()`

The docker logs are only listing requests to the cite, which are not helpful in debuging this Problem. Reverting back to 5.9.0, which I had previously, does not help. Downloading the PDFs works fine, so it seems they are not broken.
I have set `privileged=true`, so that shouldn't be a problem.

I have seen that the problem should have been solved with the fix proposed by @nicolasshu in #10  , but sadly my instance is still "broken". Is there a way to fix this?

**Comment by cgrima** [comment]
Yes, it sounds similar to what @nicolasshu reported in #10 (now in #12). His solution has been implemented in release [5.9.2.a](https://github.com/cgrima/docker_i-librarian/releases/tag/5.9.2.a). Is that the release you use?

**Comment by cgrima** [comment]
Also, if  [5.9.2.a](https://github.com/cgrima/docker_i-librarian/releases/tag/5.9.2.a) does not work, revert back to [5.8.0](https://github.com/cgrima/docker_i-librarian/releases/tag/5.8.0) since the issue might have been introduced by [5.9.0](https://github.com/mkucej/i-librarian-free/releases/tag/5.9.0) through the addition of _"better quality PDF rendering in Webkit browsers"_.

**Comment by nicolasshu** [comment]
I think your error is different from the one I had. I had the error shown in [here](https://github.com/cgrima/docker_i-librarian/issues/9#issuecomment-887893286). Your `Failed to load resource: ... 500 ()`, is that an error that shows up on the GET request from your browser? Can you provide a screenshot?

**Comment by arunoruto** [comment]
Seems like it was an obvious mistake from my side.
I used the `lastest` tag in docker-compose to fetch the image. Somehow it made an update so I thought it downloaded the `5.9.2.a` image, but it was still on `5.9.2` and had to explicitly tell him to download the never image with a tag.
@nicolasshu I think thats the same thing you experienced and @cgrima has been using the patched version instead of the `latest` tag.
