### ISSUE TITLE
Access fails from Nginx reverse proxy, works from localhost

### ISSUE THREAD

**Issue by neilzebub** [grimy55/docker_i-librarian#14]
Hello!

Please excuse me, I am extremely new to linux, nginx, docker, self-hosted etc.

I was able to create the container and can access it using http://localhost:port, however my accessing from my website via reverse proxy fails.
I am able to access the i-librarian login screen, but after entering credentials I receive an error 405 message "OOPS Request method must be POST". I imagine that it has to do with the configuration of my nginx conf file for this container, but to rectify it I am completely lost. I attached a screenshot of my conf. 

I would appreciate any ideas for next steps!!

Thank you.
![Capture](https://user-images.githubusercontent.com/87769841/141514826-a4f1ff34-b910-4c8a-b5e1-d57f3a3d7a89.PNG)

**Comment by cgrima** [comment]
I won't be able to debug a nginx config file in a timely manner. Like many docker users, I expose my images to the web through SSL by using a combination of [jwilder/nginx-proxy](https://hub.docker.com/r/jwilder/nginx-proxy) and [jrcs/letsencrypt-nginx-proxy-companion](https://hub.docker.com/r/jrcs/letsencrypt-nginx-proxy-companion) (which I've just found out is deprecated and is now replaced by [nginxproxy/acme-companion](https://hub.docker.com/r/nginxproxy/acme-companion)). That's something you might consider.
