### ISSUE TITLE
arm support

### ISSUE THREAD

**Issue by joao8545** [grimy55/docker_i-librarian#15]
After running `docker compose up -d` I receive the following output in my raspberry pi 5
`! app The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested`

Is it possible to provide an image for this architecture? Or if one already exists, could you provide me the link?
Thanks in advance!

**Comment by cgrima** [comment]
Thanks for reporting this. I've never tried to implement a docker image for another architecture. Maybe you know a comprehensive resource to do that? If I do so, I would need you to test the implementation because I do not have this architecture available on my hand. But you can also pull request your own implementation to this repo if you prefer.

**Comment by joao8545** [comment]
I actually don't really know how you could do it. After posting this I actually had the idea to build one myself, so I do have a working image for the arm architecture. I don't really know if this image would help you in anyway, but if there is a way I can send it to you. In case you end up building one for this or newer version, I would love to help you test them

**Comment by cgrima** [comment]
Yes, you can copy-paste your dockerfile here in this thread and I'll see what I can do. Thank you for agreeing to beta test.

**Comment by nakkaya** [comment]
No need to change anything in the repo, You can build it for multiple architectures in one go. Deployed to my server using, 

    docker buildx build --push -f Dockerfile --tag "ghcr.io/nakkaya/i-librarian:5.11.1" --platform linux/amd64,linux/arm64 .

**Comment by cgrima** [comment]
Good to know, thanks!
