### ISSUE TITLE
Provide tags on Docker Hub

### ISSUE THREAD

**Issue by StreakyCobra** [grimy55/docker_i-librarian#3]
Hi,

Thanks for sharing this container.

Do you mind to provide tags on the Docker Hub? There is [only `latest` yet](https://registry.hub.docker.com/u/grimy55/i-librarian/tags/manage/), could be nice to have versions, like `3.4.1`, for installing a specific version.

**Comment by cgrima** [comment]
That's a good point. Actually, I don't know how to do that smoothly. Do you have a reference?

**Comment by StreakyCobra** [comment]
I never did it myself, but I suppose something like:

```
docker build -t grimy55/i-librarian:3.4.1 .
docker push grimy55/i-librarian:3.4.1
```

would work. [It also seems](http://stackoverflow.com/a/27643254) that `latest` tag is not automatically updated, so 2 commands will be needed later.

**Comment by cgrima** [comment]
I see. the Dockerfile is actually pushed to GitHub, and then automatically synchronized from GitHub to DockerHub. I would want to keep it this way, i.e. GitHub is the main node as for my other projects.

I'll see for the next I-Librarian release what I can do for tagging during the GitHub-to-DockerHub sync.

**Comment by cgrima** [comment]
Docker Hub tags are now provided from 4.10 onward.
