### ISSUE TITLE
Prerequisite-Instructions are obsolete

### ISSUE THREAD

**Issue by gr4nt3d** [grimy55/docker_i-librarian#7]
I am referring to this:
```
wget -O i-librarian.tar.xz http://i-librarian.net/downloads/I,-Librarian-4.8-Linux.tar.xz
unxz i-librarian.tar.xz && tar -xvf i-librarian.tar library && rm i-librarian.tar
sudo chown -R www-data:www-data library
sudo chown root:root library/.htaccess
```
The URL leads to a [404 page](http://i-librarian.net/downloads/I,-Librarian-4.8-Linux.tar.xz). I suppose the files were move to [GitHub](https://github.com/mkucej/i-librarian-free/releases/tag/5.2.1).

**Comment by cgrima** [comment]
You are right the installation files are now hosted on GitHub. Try the prerequisite instructions provided by the last push.
