### ISSUE TITLE
500 Internal Server Error

### ISSUE THREAD

**Issue by Stybyk** [grimy55/docker_i-librarian#8]
Hello,
I tried to rebuild this image on my raspberry pi 4 because it´s originally made on amd64 and not worked on the arm.
The server starts well and I am able to make users and upload pdf, but when i tried to open some file I am getting error:

``
Argument` 3 passed to Librarian\Security\Validation::intRange() must be of the type int, float given, called in /app/classes/security/validation.php on line 289.
``
Any idea what can be wrong? And why it happened only on arm build?
The installation log file is too big to upload into Pastebin. Any idea where I can upload the file to share with others to analyze?

**Comment by Stybyk** [comment]
Hello,
- upgraded librarian 5.6.1 doesn't help,
- log from image building were added to my fork of this repo.
https://github.com/Stybyk/docker_i-librarian/blob/master/install.log
-eror message when i try open to pdf file looks like this : 
<a href="https://imgbb.com/"><img src="https://i.ibb.co/qxHkgDK/servereror.jpg" alt="servereror" border="0"></a>

Ideas will be welcome, thank you.

**Comment by cgrima** [comment]
It sounds to be an I, Librarian internal error to me. I see you have posted the issue [ mkucej /
i-librarian-free](https://github.com/mkucej/i-librarian-free/issues/48). Let's see what they say there.

**Comment by cgrima** [comment]
Fixed by https://github.com/mkucej/i-librarian-free/issues/48
