### ISSUE TITLE
Update the Docker Image

### ISSUE THREAD

**Issue by nicolasshu** [grimy55/docker_i-librarian#9]
Hi!
Could I make a request to update the version from 5.8.0 to 5.9.2?

Thank you so much!

**Comment by cgrima** [comment]
Sorry for being late at pushing the last updates. It should be done now on both Github and Dockerhub.

**Comment by nicolasshu** [comment]
Nah, you're perfect! Thank you!

**Comment by nicolasshu** [comment]
It looks like the upgrade has a mismatch on the PDF viewer. 
When I look at a locally installed I, Librarian, I can use their PDF viewer as this:
![locally_installed](https://user-images.githubusercontent.com/12994607/127233251-beca98d1-d68c-458c-a6a7-7669fba41513.png)

But when I use the Docker one, it looks like this:
![docker_installed](https://user-images.githubusercontent.com/12994607/127233306-3ffaf741-2d7c-4c5e-9e4d-1eb3da2d3643.png)

Do you think this is because of a lib package?

**Comment by cgrima** [comment]
I also use the 5.9.2 Docker image since yesterday, but I did not encounter this issue. Could you check in the `administrator/Software Details` if every dependencies have been installed properly?

Here is my example:
![image](https://user-images.githubusercontent.com/839552/127236425-8f071c40-3f50-48ac-9014-12336e48b422.png)

**Comment by nicolasshu** [comment]
So I was looking into it further. When I went to inspect the site loading, as it loaded each page, it failed to run the `imagecreatefromjpeg()` used in PHP 7.4.21. 

```
Call to undefined function Librarian\Media\imagecreatefromjpeg(). 
```

As I looked further, it looked as one needed to now configure the `gd` extension on PHP to use the tags `--with-freetype` and `--with-jpeg`. So I went into the container using `docker exec` and ran the commands below based on [this](https://stackoverflow.com/a/68115239/4962905)

```
docker-php-ext-configure gd --with-freetype=/usr/include/ --with-jpeg=/usr/include
docker-php-ext-install gd
```

So I think that you might need to add 

```
RUN docker-php-ext-configure gd --with-freetype=/usr/include/ --with-jpeg=/usr/include
```

I'll create a pull request and please double check me

**Comment by nicolasshu** [comment]
It looks like it works now

![solved](https://user-images.githubusercontent.com/12994607/127237968-f0f40f88-0ad2-495e-9922-3f2635ca29e7.png)

**Comment by nicolasshu** [comment]
Sorry, I only now just saw your previous comment. I spun up a new container just to see what would happen if I started fresh, and this is the dependencies page:

![probs2](https://user-images.githubusercontent.com/12994607/127238948-15709c88-3438-49c2-88a9-6d240fb702d8.png)

However, when I went to see if it could load a PDF using its viewer, I saw this:
![probs](https://user-images.githubusercontent.com/12994607/127238967-df73a449-8053-41c3-8e47-4bc5a33f9907.png)

where if I went to inspect it, I would see this problem:
![probs3](https://user-images.githubusercontent.com/12994607/127239051-ee4745b0-3123-48a9-a6de-d0ca12e8c2e2.png)
